### ISSUE TITLE
It is not Rails

### ISSUE THREAD

**Issue by marceloboeira** [cristianoliveira/apitogo#2]

**Comment by cristianoliveira** [comment]
I haven't done in Rails just because it would require ruby installed 😞 

Using go I can distribute the binary so no dependencies 😄

**Comment by marceloboeira** [comment]
rails/rails#1

**Comment by marceloboeira** [comment]
> Using go I can distribute the binary so no dependencies

@cristianoliveira you have used crystal, you have a readable code and bin with no deps 👍

**Comment by cristianoliveira** [comment]
I know that memorable first rails issue created by a pythonist 😆 

Golang is way more stable than Crystal you know that.

**Comment by marceloboeira** [comment]
Stable enough for this task.

**Comment by cristianoliveira** [comment]
Plus using go I could made the pun apitoGO hahahaha 

<img src="https://media.giphy.com/media/immL5CvVZSyQw/giphy.gif" width="480" height="307">

**Comment by marceloboeira** [comment]
hahahahahah you are the first one to find a use for Go lang: Funny names.
